### ISSUE TITLE
TransOver is not working on Youtube.

### ISSUE THREAD

**Issue by ardahansenses** [artemave/translate_onhover#101]
"Hello, the TransOver extension was extremely helpful to me in translating subtitles while watching videos on Youtube. However, it seems to have stopped working after the latest update. This is very important to me, could you fix the problem?"

**Comment by artemave** [comment]
Hello. What browser? It works for me in Firefox and Brave (chrome).

**Comment by ardahansenses** [comment]
Hey. It is Google Chrome version of 108.0.5359.125 64Bit. And maybe it
could be helpful: [image: image.png]

artem avetisyan ***@***.***>, 20 Ara 2022 Sal, 12:17
tarihinde şunu yazdı:

**Comment by artemave** [comment]
Ok. I can see it. Will see if I can fix it.

**Comment by ardahansenses** [comment]
Thank you very much, it is really very important for me. Good luck.

20 Ara 2022 Sal, saat 12:41 tarihinde artem avetisyan <
***@***.***> şunu yazdı:

**Comment by artemave** [comment]
I submitted a fix to the chrome store. It normally takes a few hours for them to publish the update.

**Comment by ardahansenses** [comment]
Great, thanks for the update. It is working now.

artem avetisyan ***@***.***>, 20 Ara 2022 Sal, 14:35
tarihinde şunu yazdı:

**Comment by artemave** [comment]
Fixed
