### ISSUE TITLE
'Only show' option doesn't take effect

### ISSUE THREAD

**Issue by madamovych** [artemave/translate_onhover#103]
I have selected 'translate when I point to a word'.
But I've also selected 'Only show word translation when I hold the ctrl key' and 'Only show selection translation when I hold the ctrl key'.
The later ones are ignored. Popup is shown when I hover the mouse.
When I click (and release) ctrl button once, this is reproducible no more for a while. But it annoys again after some time.

Was able 'to make it reproducible' after navigating Chrome tabs using 'ctrl + pgup' or 'ctrl + pgdn'. After these keystrokes popup appear again on mouse hover

**Comment by artemave** [comment]
Works as expected for me: I can see popup for as long as I hold ctrl (and move the mouse around). I don't see popup when control is released.

**Comment by madamovych** [comment]
Even in Chrome after you navigate different tabs with ctrl+pgdn and ctrl+pgup?

**Comment by artemave** [comment]
Ah, missed that detail. I can now see the problem.

**Comment by madamovych** [comment]
works for me. Thank you very much! 
5 stars is yours
