### ISSUE TITLE
There is an issue

### ISSUE THREAD

**Issue by ardahansenses** [artemave/translate_onhover#104]
Hey again, it is not working on Google Chrome after new update.

I think these details would be helpful. Please fix it, this extension very important for me. Thank you very much.
![image](https://user-images.githubusercontent.com/43324803/210172209-08e0f0a7-edb2-4065-8353-7e32769f7f05.png)

![image](https://user-images.githubusercontent.com/43324803/210172169-1f686e80-8481-4019-aa65-533ca95e83cf.png)

**Comment by artemave** [comment]
Does it still happen after page reload? I've seen this error after extension updates.

**Comment by ardahansenses** [comment]
Wow, it is not occur after reload, it is working now. Very interesting. There is no need any solution anymore i think. Thank you very much.
