### ISSUE TITLE
No translation for native language website

### ISSUE THREAD

**Issue by hugodessomme** [artemave/translate_onhover#23]
Hello,

I think another option should be added to select when the extension should not be enabled for a language. I even think it could be interesting to be able to select several languages we don't want to translate. I understand we can select the "only show translation word when i click xxx" option, but maybe my proposition could be another alternative.

For example, I am French, I don't need to translate words on a french website.

What's your opinion ?

Thank you.

**Comment by artemave** [comment]
> For example, I am French, I don't need to translate words on a french website.

Have you tried "reverse translate"? On a french website it would translate french to the "translate from" language. I find it useful.

**Comment by Supuhstar** [comment]
Multilingual support would be nice. I speak English and Spanish, so there's no need to translate those.
