### ISSUE TITLE
TTS глюченый

### ISSUE THREAD

**Issue by sooqua** [artemave/translate_onhover#27]
Искал просто TTS, а нашел отличную замену стандартному hover-to-translate от гугла.
К сожалению, но TTS оказался глюченым - при удерживании клавиши активации TTS гугл-чувак начинает повторять выделенную фразу снова и снова, пока не выключишь сие расширение. Количество повторов, кажется, растет со скорость, с которой любая клавиша в Windows повторяется в нажатом состоянииииииииииииииииииииииииииииииииииииииииии - очень быстро.
Был очень удивлен тем что данный баг до сих пор не был обнаружен. Пожалуйста, исправьте.

**Comment by artemave** [comment]
Спасибо! Исправим.
