### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by tonank** [artemave/translate_onhover#34]
Hi, the only thing I truly lack when using Firefox, compared to Chrome is Transover - a truly awesome extension.

I tried about 20 alternatives, and they all are waay behind.

Please consider porting it.

**Comment by artemave** [comment]
Thank you very much - I am glad you find it so useful. There are two problems with firefox port:

- it requires time that I don't have
- transover is using google translate api. It is a paid api, but I am not paying. I am basically stealing it. Google can shut us down at any point (quite rightfully so)

**Comment by tjweber** [comment]
Awesome response.... admitting you are stealing the API.  :)

I 2nd the vote to port to Firefox, especially since the new one was just released.  Perhaps allow some other developers to work alongside you?

**Comment by id-den** [comment]
+1 vote for use in FF.

**Comment by artemave** [comment]
@tjweber this is github: clone the project, hack hack hack, open pull request when you're done.

**Comment by aabgaryan** [comment]
Hey folks! Here is a solution for ffx`
Download "[Chrome Store Foxified](https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/)" and then go to [Trans Over's Chrome Store page](https://chrome.google.com/webstore/detail/transover/aggiiclaiamajehmlfpkjmlbadmkledi) and add it to ffx. ;)

@artmave if you click on word several times the **same** hint will appear again without cleaning up previews one. Follow to the shadow under the hint and you'll see the result. 
Շնորհակալություն թույն extension-ի համար ;)

**Comment by artemave** [comment]
I tried foxified and it didn't work. That said, it gave me a handful of validation errors so that would be a good start. Also it looks like it will be less effort than I thought. So might actually happen!

**Comment by aabgaryan** [comment]
@artemave Any news on firefox port ?

**Comment by LokiNaBoki** [comment]
As an firefox alternative i can recommend: [Simple translate](https://addons.mozilla.org/en-US/firefox/addon/simple-translate/?src=search)

**Comment by artemave** [comment]
Done https://addons.mozilla.org/en-US/firefox/addon/transover-ff/
