### ISSUE TITLE
 Uncaught TypeError: Cannot read property 'delay' of undefined

### ISSUE THREAD

**Issue by msalahz** [artemave/translate_onhover#42]
Hello! I'm getting the following error everywhere and it drive my crazy 
` Uncaught TypeError: Cannot read property 'delay' of undefined`

the source of error is chrome-extension://aggiiclaiamajehmlfpkjmlbadmkledi/contentscript.js

Can you advice ?

**Comment by artemave** [comment]
Hello. Does this error break transover? Could you provide a stacktrace?

**Comment by artemave** [comment]
I believe this is fixed now
