### ISSUE TITLE
Change translate apı url

### ISSUE THREAD

**Issue by mozkan007** [artemave/translate_onhover#44]
Hi, I am using v1.44 and the extension does not work when I connect to internet with vpn extension on Chrome. I guess you need to change apı url because this issue occurred on v1.42 and you solved it using this method. Thanks.

**Comment by artemave** [comment]
Please provide more debugging information. This ticket is a good example of what I'd need to investigate the problem.

**Comment by mozkan007** [comment]
What kind of an information should I provide you? Because I am an ordinary PC user I do not have any technical knowledge about the programming.Sorry.

**Comment by artemave** [comment]
Sorry, I forgot to attach the link to my previous message: 

_This ticket is a good example of what I'd need to investigate the problem - https://github.com/artemave/translate_onhover/issues/40_

**Comment by mozkan007** [comment]
Hi again. The issue occurs when I open vpn extension on chrome but there is no problem when I use external vpn software or without vpn. Here is a screenshot. I hope this is what you need. Thanks.
![Capture](https://user-images.githubusercontent.com/16270347/57201599-bb0c2b00-6fa3-11e9-94f9-c91ca09dcbb3.JPG)

**Comment by artemave** [comment]
Could you please clear the console (little crossed circle button), turn on vpn extension, try to use transover few times and then paste a screenshot.

**Comment by mozkan007** [comment]
I took a screenshot as you said above.
![Capture](https://user-images.githubusercontent.com/16270347/57214132-a5255700-6ff1-11e9-84b1-b6959594b65c.JPG)

**Comment by artemave** [comment]
So, "background" script appears to be working fine. Could you now make a screenshot of the DevTools console but on the page you're visiting? If you're on Windows, press CTRL-Shift-i, you'll see a similar UI to the one in the screenshot above. Choose "Console", clear, and then attempt to use tranvsover.

**Comment by artemave** [comment]
Also, what's the vpn extension?

**Comment by mozkan007** [comment]
I am using windscribe extension and I added the screenshot you want above. Thanks.
![Capture](https://user-images.githubusercontent.com/16270347/57258736-eb1c0280-7065-11e9-8527-c55653fe7e5f.JPG)

**Comment by artemave** [comment]
Amon Amarth - nice!

I installed and activated that extension, transover is still working. Could you give me a link to that website?

**Comment by mozkan007** [comment]
Hi, I am trying now again and it is working with the extension at the moment. I guess there was a problem with the extension. Thanks.
