### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by cellurl3** [artemave/translate_onhover#59]
![image](https://user-images.githubusercontent.com/53091899/90679108-4f47e300-e225-11ea-9641-0741416f08d3.png)

**Comment by cellurl3** [comment]
i know i am doing something stupid, like I didnt have the jquery.min.js , etc. Found those, but these I need help understanding.

Thanks for a great app.

**Comment by artemave** [comment]
What browser are you using? Because it works fine in Brave/Chrome

**Comment by cellurl3** [comment]
I'm in chrome. I downloaded the zip and added the jQuery.min.js and the
other JS file and loaded it unpacked developer mode of course and that's
the error I got. I'll try it on another chrome in a in a couple minutes.
Thanks for the dialogue

**Comment by artemave** [comment]
Oh, you mean dev version. I've updated project readme.

**Comment by cellurl3** [comment]
I am on different windows box..  Chrome  Version 84.0.4147.125 (Official Build) (64-bit)
i get different error.

btw: this is where I got this. Hope thats ok??
http://xregexp.com/v/3.2.0/xregexp-all.js

![image](https://user-images.githubusercontent.com/53091899/90689946-75c24a00-e236-11ea-8963-6356c5531841.png)
