### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by cellurl3** [artemave/translate_onhover#60]
i am on a different windows box.   Chrome Version 84.0.4147.125 (Official Build) (64-bit)

BTW, this is where I got this. Hope thats ok??
http://xregexp.com/v/3.2.0/xregexp-all.js

I get different errors. Thanks for continued help.
![image](https://user-images.githubusercontent.com/53091899/90690200-e49fa300-e236-11ea-9593-c7f228f10381.png)
![image](https://user-images.githubusercontent.com/53091899/90690253-fed98100-e236-11ea-8e2b-4fe73aad75d2.png)
and four of these errors
![image](https://user-images.githubusercontent.com/53091899/90690299-144eab00-e237-11ea-8f71-67855ceb914c.png)

**Comment by cellurl3** [comment]
![image](https://user-images.githubusercontent.com/53091899/90690560-88894e80-e237-11ea-8bce-e79302357a01.png)

**Comment by cellurl3** [comment]
ima going to get node.js (sorry i missed that....)

**Comment by cellurl3** [comment]
![image](https://user-images.githubusercontent.com/53091899/90692232-6513d300-e23a-11ea-8e5a-e634cdb77387.png)

**Comment by cellurl3** [comment]
please mark this non issue closed....

I started over. Amazing setup you guys created!
Peace.

**Comment by WofWca** [comment]
This an ordinary NPM project, and it's set up like one.

You can close the issue yourself.
