### ISSUE TITLE
doesnt register numbers like 1234

### ISSUE THREAD

**Issue by cellurl3** [artemave/translate_onhover#63]
Looking at console, it seems to get numbers not always.
![image](https://user-images.githubusercontent.com/53091899/92677815-3db89f00-f2ea-11ea-8155-ce061a20f708.png)

I am set to hoover-over, not click.
Words light up normally, but hoovering over a number like 1234 doesnt "hit".
If I click and highlight the number it works, but then it gets stuck just registering the hightlighted number forever until I unhighlight it.

No biggie, but I am more interested in numbers sometimes....

Q: Where is your tip jar??

**Comment by artemave** [comment]
Yeah I don't think numbers were ever meant to work. I mean, you know that '1234' is '1234'. Don't need to translate that, do you?

**Comment by cellurl3** [comment]
Curious how the code knows to not send it to the webservice??

**Comment by artemave** [comment]
Using regular expression. If something under the cursor looks like a word, translate it.
