### ISSUE TITLE
Перестал переводить

### ISSUE THREAD

**Issue by stasvas** [artemave/translate_onhover#71]
Здравствуйте @artemave, прежде всего спасибо за это прекрасное расширение, уже много лет пользуюсь, очень выручает!

Однако сегодня столкнулся с тем, что расширение перестало переводить текст с любого языка (всегда показывает надпись, что перевод не найден). Кажется, это что-то с API наверное случилось? Проверял как в своем "родном" хроме, так и в фаерфоксе - результат один и тот же. Хотя если никто больше не пожаловался на эту проблему, возможно это только у меня так, но как тогда это поправить? Есть ли режим дебага или что-то вроде этого? Может быть я с ограничениями столкнулся и меня решили "забанить"?

**Comment by Guy1524** [comment]
It's not just you, the service is broken for me too.

**Comment by Dwidy99** [comment]
Yes, me too.

**Comment by riodarmawan** [comment]
Oh my God, I have 25 left before the exam. I really need this extension to study, very helpful for translating my material. thank you, hope it will be fixed soon :)

**Comment by artemave** [comment]
Thanks for reporting! I can see the problem. Will keep you posted.

**Comment by artemave** [comment]
Fixed the problem. Submitted new version to both Chrome and Firefox stores. New version is already available in [Firefox](https://addons.mozilla.org/en-US/firefox/addon/transover-ff/). But Chrome review is always a bit of a gamble, so stay tuned.

**Comment by stasvas** [comment]
@artemave спасибо! Однако при установке расширения происходит ошибка:

![image](https://user-images.githubusercontent.com/78857716/111625616-1b09c480-87fe-11eb-9ddf-61aaefcec463.png)

**Comment by artemave** [comment]
Yeah, that's bizarre. webpack in production mode results in this error (strips off new lines?). Anyway, you can build with `yarn dev` and that works.

I'll submit another version.

**Comment by stasvas** [comment]
Ура, расширение снова работает, спасибо @artemave!

**Comment by stasvas** [comment]
Что-то снова перестало работать, теперь вообще не показывается даже попап :(((
Есть ли способ отладки расширения, чтобы понять, в чем причина?

**Comment by artemave** [comment]
Здесь что-нибудь пишут интересное?

![Screenshot from 2021-03-18 17-04-52](https://user-images.githubusercontent.com/23721/111657820-151ae000-880c-11eb-975d-474097285ba4.png)

![image](https://user-images.githubusercontent.com/23721/111657922-2bc13700-880c-11eb-9069-4c7fabb56c9a.png)

![Screenshot from 2021-03-18 17-07-47](https://user-images.githubusercontent.com/23721/111658281-7c389480-880c-11eb-983d-208e59448749.png)

**Comment by stasvas** [comment]
Да, вот приложил скриншот

![image](https://user-images.githubusercontent.com/78857716/111681541-68088d80-8834-11eb-9bf0-98a8a171450e.png)

Пробовал с французского перевести кое-что, раньше переводил, теперь даже всплывашки нет. Видимо они ограничение какое-нибудь ввели?

**Comment by stasvas** [comment]
Теперь снова заработал, на том же тексте. Сегодня после установки исправленной версии то же самое было, потом заработало вновь, и снова отвалился (тогда я прислал скриншот). Значит, там наверное ограничения на количество запросов добавили, потому что раньше таких проблем не было.

**Comment by artemave** [comment]
Да, похоже на ограничение запросов https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429
