### ISSUE TITLE
vivaldi 3.7

### ISSUE THREAD

**Issue by urfausto** [artemave/translate_onhover#72]
Hi, with latest version of vivaldi browser the extension stopped working. any help on this?

**Comment by artemave** [comment]
Hello,

The fix has been submitted to Chrome and Firefox stores. It might take some time for the update to get through Chrome review. Meanwhile, it's already available on Firefox.

**Comment by urfausto** [comment]
> The fix has been submitted to Chrome

ah ok, thanks for the swift reply. can you please share the number of this new version?

**Comment by artemave** [comment]
1.55

**Comment by urfausto** [comment]
@artemave i have this one already. there is another different bug then, which is not the same you are talking about.

https://chrome.google.com/webstore/detail/transover/aggiiclaiamajehmlfpkjmlbadmkledi

**Comment by urfausto** [comment]
for a small glimpse i have casually seen a translation baloon, but it disappeard very quickly.

**Comment by urfausto** [comment]
@artemave i need this extension, i have to do translation work... and now i can't.

**Comment by artemave** [comment]
The fix has been submitted to the store. Meanwhile you can download this repo and use local version or try Firefox

**Comment by urfausto** [comment]
@artemave 1.55 is already available from the store. and i have that version. or is the fixed version the same number?
