### ISSUE TITLE
new version and chromium browsers

### ISSUE THREAD

**Issue by urfausto** [artemave/translate_onhover#73]
version 1.55 doesn't work anymore within chromium browsers

@artemave

**Comment by artemave** [comment]
It's possible that you're being rate limited. In which case, it will resume working soon.

See details here: https://github.com/artemave/translate_onhover/issues/71#issuecomment-802206431

**Comment by urfausto** [comment]
ok thanks, so i just need to wait? i hope so.

**Comment by urfausto** [comment]
it doesn't work at all for chrome too.
