### ISSUE TITLE
TransOver not working

### ISSUE THREAD

**Issue by riodarmawan** [artemave/translate_onhover#78]
I block a text and the transover doesn't show the translation

**Comment by riodarmawan** [comment]
now it's working again, for some time ago the transover doesn't work

**Comment by riodarmawan** [comment]
now suddenly it doesn't work anymore

**Comment by artemave** [comment]
Google translate API must be rate limiting you. Unfortunately, at this moment, I there is not much that can be done. You can probably work around the block somewhat by using vpn/tethering.

I am working on a fix but it'll take some time.

See #74

**Comment by riodarmawan** [comment]
thanks dude...
