### ISSUE TITLE
Error! Too many requests - translation is temporary disabled

### ISSUE THREAD

**Issue by erata** [artemave/translate_onhover#80]
The app translates well at the beginning. After translating 5-10 words, it starts to make an error. The error message is as follows: 
**Error! Too many requests - translation is temporary disabled**

![image](https://user-images.githubusercontent.com/3416873/116763283-8d84db80-aa1d-11eb-9259-e18eb3f1035a.png)

**Comment by artemave** [comment]
Fixed in 1.59 (just submitted to chrome store - may take few days to appear)
