### ISSUE TITLE
Direction of undefined

### ISSUE THREAD

**Issue by BuljaBulja** [artemave/translate_onhover#88]
After last update plugin do not work for me anymore.
I'm getting error "Cannot read properties of undefined"
<img width="610" alt="Screenshot 2022-01-19 at 10 33 59" src="https://user-images.githubusercontent.com/7819861/150093813-293b56a6-2a58-4338-b738-5918581be142.png">

**Comment by BuljaBulja** [comment]
My bad. target language was deselected. Thanks

**Comment by artemave** [comment]
Are you saying that target language got deselected on its own after the update? That's a bit of a worry.
