### ISSUE TITLE
Popup appears barely on firefox

### ISSUE THREAD

**Issue by trisadmeslek** [artemave/translate_onhover#90]
Hello Friend, 

With your last update; when I select a text, it doesn't show popup until I move mouse several times or more on the text. If I am not wrong, you fixed popup issue that appears two times but it seems like something has broken. 

Browser with version : Firefox 96.0.2

Thanks

**Comment by artemave** [comment]
Thanks for reporting! I can see the issue. I refactored background script to use promises instead of callbacks and forgot to await in couple of places. Classic.
