### ISSUE TITLE
TransOver not working

### ISSUE THREAD

**Issue by MZlatev-MDigital** [artemave/translate_onhover#91]
Hi since a month or two I have been experiencing issues with the plugin TransOver.
The popup window with the translation no longer appears when I click the alt key.

I am running Google Chrome Version 97.0.4692.71 (Official Build) (64-bit) on Ubuntu 20.04.3 LTS

**Comment by MZlatev-MDigital** [comment]
I managed to get it working.
I had to update the plugin permissions. It seems at some point those became backwards incompatible with Google Chrome.
![image](https://user-images.githubusercontent.com/76939603/152159742-e2a377ab-cebe-4eef-9f5a-4ff0e98e22f8.png)

**Comment by artemave** [comment]
Oh, that's interesting. I haven't changed those permissions for eons, but I have added "storage" permission recently, so I wonder if that somehow had this side effect. But that's a complete stab in the dark. Thanks for reporting! There is a steady stream of frustrated reviews on Chrome store. I'll now be able to tell them something useful to try.
